# Generated by Django 2.2.6 on 2019-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20191029_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='Kimberly Ryan', max_length=64, verbose_name='昵称'),
        ),
    ]
