# Generated by Django 2.2.6 on 2019-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20191029_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='Melissa Martin', max_length=64, verbose_name='昵称'),
        ),
    ]
