# Generated by Django 2.2.6 on 2019-10-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_auto_20191029_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='John Nguyen', max_length=64, verbose_name='昵称'),
        ),
    ]
